# Generated by Django 4.2 on 2023-06-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('button_text', models.CharField(max_length=30)),
                ('years_text', models.CharField(max_length=15)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.language')),
            ],
        ),
    ]
