# Generated by Django 4.2 on 2023-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_websitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='appearance_label',
            field=models.CharField(default='Appearance', max_length=30),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='care_label',
            field=models.CharField(default='Care', max_length=30),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='character_label',
            field=models.CharField(default='Character', max_length=30),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='colors_text',
            field=models.CharField(default='Colors', max_length=30),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='difficulty_text',
            field=models.CharField(default='Difficulty', max_length=30),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='pattern_text',
            field=models.CharField(default='Patterns', max_length=30),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='traits_text',
            field=models.CharField(default='Traits', max_length=30),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
