# Generated by Django 4.2 on 2023-06-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_websitecontent_appearance_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='cats/media/'),
        ),
    ]
